services:
  db:
    image: postgres
    volumes:
      - ./tmp/postgres_data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data
    ports:
      - 6379:6379
  rails:
    build: ./rails
    volumes:
      - ./rails/sport_betting:/rails 
      - gem_cache:/usr/local/bundle
      - rails_node_modules:/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres@db:5432/sports_betting
      - REDIS_URL=redis://redis:6379/0
  node:
    build: ./node
    volumes:
      - ./node:/app
      - node_node_modules:/app/node_modules
    ports:
      - 3001:3000
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
volumes:
  gem_cache:
    driver: local
  rails_node_modules:
    driver: local
  node_node_modules:
    driver: local
